In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance.csv")

In [3]:
dataset.head(5)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
dataset.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
age         1338 non-null int64
sex         1338 non-null object
bmi         1338 non-null float64
children    1338 non-null int64
smoker      1338 non-null object
region      1338 non-null object
charges     1338 non-null float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.2+ KB


In [6]:
x=dataset.iloc[:,0:6].values
y=dataset.iloc[:,6].values

In [7]:
x

array([[19, 'female', 27.9, 0, 'yes', 'southwest'],
       [18, 'male', 33.77, 1, 'no', 'southeast'],
       [28, 'male', 33.0, 3, 'no', 'southeast'],
       ...,
       [18, 'female', 36.85, 0, 'no', 'southeast'],
       [21, 'female', 25.8, 0, 'no', 'southwest'],
       [61, 'female', 29.07, 0, 'yes', 'northwest']], dtype=object)

In [8]:
y

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[1,4,5])],remainder="passthrough")
#coverts data into binary form
x=ct.fit_transform(x)

In [10]:
x.shape

(1338, 11)

In [11]:
y.shape

(1338,)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) #test_size=0.2 is 20% testing data

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [14]:
from tensorflow.keras.models import Sequential #used to initialize
from tensorflow.keras.layers import Dense #used to add layers

In [15]:
reg=Sequential()

In [16]:
reg.add(Dense(6,kernel_initializer ="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [17]:
reg.add(Dense(12,kernel_initializer ="random_uniform",activation="relu"))

In [18]:
reg.add(Dense(1,kernel_initializer ="random_uniform",activation="relu"))

In [19]:
reg.compile("adam","mean_squared_error",metrics=["mse"]) #nick name for batch gradient is adam.

In [20]:
reg.fit(x_train,y_train,batch_size=32,epochs=1000)

Epoch 1/1000
1070/1070 [==============================] - 0s 148us/sample - loss: 317636706.8710 - mean_squared_error: 317636768.0000
Epoch 2/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 317633943.2075 - mean_squared_error: 317633984.0000
Epoch 3/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 317626433.3458 - mean_squared_error: 317626464.0000
Epoch 4/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 317608855.7009 - mean_squared_error: 317608832.0000
Epoch 5/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 317572573.0093 - mean_squared_error: 317572576.0000
Epoch 6/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 317511293.9065 - mean_squared_error: 317511264.0000
Epoch 7/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 317413873.1664 - mean_squared_error: 317413888.0000
Epoch 8/1000
1070/1070 [==============================] - 0s 35us/sa

1070/1070 [==============================] - 0s 34us/sample - loss: 180423030.6542 - mean_squared_error: 180423040.0000
Epoch 62/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 176232344.8523 - mean_squared_error: 176232336.0000
Epoch 63/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 171959022.4449 - mean_squared_error: 171959008.0000
Epoch 64/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 167771679.5215 - mean_squared_error: 167771696.0000
Epoch 65/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 163639439.6112 - mean_squared_error: 163639440.0000
Epoch 66/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 159476614.3103 - mean_squared_error: 159476624.0000
Epoch 67/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 155408232.0748 - mean_squared_error: 155408256.0000
Epoch 68/1000
1070/1070 [==============================] - 0s 30us/sample - 

1070/1070 [==============================] - 0s 31us/sample - loss: 47338065.4804 - mean_squared_error: 47338064.0000
Epoch 123/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 46911576.1495 - mean_squared_error: 46911576.0000
Epoch 124/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 46496053.7196 - mean_squared_error: 46496056.0000
Epoch 125/1000
1070/1070 [==============================] - 0s 28us/sample - loss: 46104439.2224 - mean_squared_error: 46104436.0000
Epoch 126/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 45704036.9720 - mean_squared_error: 45704032.0000
Epoch 127/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 45339650.6318 - mean_squared_error: 45339652.0000
Epoch 128/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 44976701.8280 - mean_squared_error: 44976700.0000
Epoch 129/1000
1070/1070 [==============================] - 0s 28us/sample - loss: 4

1070/1070 [==============================] - 0s 30us/sample - loss: 35407070.4299 - mean_squared_error: 35407072.0000
Epoch 184/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 35351404.8673 - mean_squared_error: 35351408.0000
Epoch 185/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 35296249.8131 - mean_squared_error: 35296252.0000
Epoch 186/1000
1070/1070 [==============================] - 0s 28us/sample - loss: 35240186.7290 - mean_squared_error: 35240192.0000
Epoch 187/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 35190055.7308 - mean_squared_error: 35190060.0000
Epoch 188/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 35135690.6093 - mean_squared_error: 35135688.0000
Epoch 189/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 35087106.2318 - mean_squared_error: 35087100.0000
Epoch 190/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 3

1070/1070 [==============================] - 0s 31us/sample - loss: 34053087.7832 - mean_squared_error: 34053084.0000
Epoch 245/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 34047994.0411 - mean_squared_error: 34047996.0000
Epoch 246/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 34040252.6897 - mean_squared_error: 34040256.0000
Epoch 247/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 34026738.3028 - mean_squared_error: 34026740.0000
Epoch 248/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 34026756.7776 - mean_squared_error: 34026756.0000
Epoch 249/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 34019168.3140 - mean_squared_error: 34019168.0000
Epoch 250/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 34015519.9103 - mean_squared_error: 34015520.0000
Epoch 251/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 3

1070/1070 [==============================] - 0s 31us/sample - loss: 33783679.1888 - mean_squared_error: 33783680.0000
Epoch 306/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33784907.6673 - mean_squared_error: 33784916.0000
Epoch 307/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 33776554.5121 - mean_squared_error: 33776552.0000
Epoch 308/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33778397.0879 - mean_squared_error: 33778400.0000
Epoch 309/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33764765.9411 - mean_squared_error: 33764768.0000
Epoch 310/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33779871.7533 - mean_squared_error: 33779872.0000
Epoch 311/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 33761411.1402 - mean_squared_error: 33761416.0000
Epoch 312/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 3

1070/1070 [==============================] - 0s 30us/sample - loss: 33643851.7570 - mean_squared_error: 33643848.0000
Epoch 367/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 33640925.0654 - mean_squared_error: 33640928.0000
Epoch 368/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 33636055.5664 - mean_squared_error: 33636056.0000
Epoch 369/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33633669.0206 - mean_squared_error: 33633668.0000
Epoch 370/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 33634613.6150 - mean_squared_error: 33634616.0000
Epoch 371/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33630747.7495 - mean_squared_error: 33630744.0000
Epoch 372/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 33631936.0224 - mean_squared_error: 33631936.0000
Epoch 373/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 3

1070/1070 [==============================] - 0s 33us/sample - loss: 33534839.0804 - mean_squared_error: 33534836.0000
Epoch 428/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33531909.4879 - mean_squared_error: 33531912.0000
Epoch 429/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33526318.9121 - mean_squared_error: 33526322.0000
Epoch 430/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33523231.7981 - mean_squared_error: 33523234.0000
Epoch 431/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33526666.6916 - mean_squared_error: 33526664.0000
Epoch 432/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 33525901.9701 - mean_squared_error: 33525906.0000
Epoch 433/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 33519763.7308 - mean_squared_error: 33519766.0000
Epoch 434/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 3

1070/1070 [==============================] - 0s 33us/sample - loss: 33432868.2617 - mean_squared_error: 33432872.0000
Epoch 489/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33426667.2692 - mean_squared_error: 33426664.0000
Epoch 490/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33432046.1458 - mean_squared_error: 33432042.0000
Epoch 491/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 33427082.7850 - mean_squared_error: 33427084.0000
Epoch 492/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33423490.6243 - mean_squared_error: 33423490.0000
Epoch 493/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 33430353.1813 - mean_squared_error: 33430354.0000
Epoch 494/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33431002.2925 - mean_squared_error: 33431004.0000
Epoch 495/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 3

1070/1070 [==============================] - 0s 30us/sample - loss: 33344917.2112 - mean_squared_error: 33344924.0000
Epoch 550/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 33342433.0645 - mean_squared_error: 33342432.0000
Epoch 551/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 33340128.6804 - mean_squared_error: 33340130.0000
Epoch 552/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 33336166.8860 - mean_squared_error: 33336162.0000
Epoch 553/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 33340935.0037 - mean_squared_error: 33340930.0000
Epoch 554/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33337956.8037 - mean_squared_error: 33337952.0000
Epoch 555/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 33332530.4037 - mean_squared_error: 33332528.0000
Epoch 556/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 3

1070/1070 [==============================] - 0s 30us/sample - loss: 33263121.1234 - mean_squared_error: 33263122.0000
Epoch 611/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 33271155.6860 - mean_squared_error: 33271154.0000
Epoch 612/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33271775.8019 - mean_squared_error: 33271778.0000
Epoch 613/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33258233.4579 - mean_squared_error: 33258234.0000
Epoch 614/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 33260828.2804 - mean_squared_error: 33260830.0000
Epoch 615/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33267009.5477 - mean_squared_error: 33267016.0000
Epoch 616/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 33258045.9645 - mean_squared_error: 33258050.0000
Epoch 617/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 3

1070/1070 [==============================] - 0s 30us/sample - loss: 33202062.9458 - mean_squared_error: 33202058.0000
Epoch 672/1000
1070/1070 [==============================] - 0s 27us/sample - loss: 33196738.7402 - mean_squared_error: 33196736.0000
Epoch 673/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 33192606.4336 - mean_squared_error: 33192610.0000
Epoch 674/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 33195956.5178 - mean_squared_error: 33195956.0000
Epoch 675/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33191344.0673 - mean_squared_error: 33191342.0000
Epoch 676/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 33188458.9869 - mean_squared_error: 33188460.0000
Epoch 677/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 33191400.1121 - mean_squared_error: 33191396.0000
Epoch 678/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 3

1070/1070 [==============================] - 0s 42us/sample - loss: 33118164.1159 - mean_squared_error: 33118166.0000
Epoch 733/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 33119625.0430 - mean_squared_error: 33119624.0000
Epoch 734/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 33119795.5514 - mean_squared_error: 33119792.0000
Epoch 735/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 33111959.2935 - mean_squared_error: 33111956.0000
Epoch 736/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 33114957.0991 - mean_squared_error: 33114950.0000
Epoch 737/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 33113660.1794 - mean_squared_error: 33113660.0000
Epoch 738/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 33111094.7963 - mean_squared_error: 33111092.0000
Epoch 739/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 3

1070/1070 [==============================] - 0s 30us/sample - loss: 33033724.7327 - mean_squared_error: 33033728.0000
Epoch 793/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 33031690.0112 - mean_squared_error: 33031682.0000
Epoch 794/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 33031956.3813 - mean_squared_error: 33031954.0000
Epoch 795/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 33034770.2579 - mean_squared_error: 33034776.0000
Epoch 796/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 33033273.5402 - mean_squared_error: 33033272.0000
Epoch 797/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 33030178.7925 - mean_squared_error: 33030182.0000
Epoch 798/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 33023619.5963 - mean_squared_error: 33023618.0000
Epoch 799/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 3

1070/1070 [==============================] - 0s 35us/sample - loss: 32917742.5832 - mean_squared_error: 32917738.0000
Epoch 854/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 32918667.5813 - mean_squared_error: 32918668.0000
Epoch 855/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 32917442.1009 - mean_squared_error: 32917442.0000
Epoch 856/1000
1070/1070 [==============================] - 0s 36us/sample - loss: 32921975.6336 - mean_squared_error: 32921972.0000
Epoch 857/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 32912849.1925 - mean_squared_error: 32912850.0000
Epoch 858/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 32918148.5121 - mean_squared_error: 32918148.0000
Epoch 859/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 32920870.2804 - mean_squared_error: 32920868.0000
Epoch 860/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 3

1070/1070 [==============================] - 0s 34us/sample - loss: 32823378.6916 - mean_squared_error: 32823380.0000
Epoch 915/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 32822883.0318 - mean_squared_error: 32822882.0000
Epoch 916/1000
1070/1070 [==============================] - 0s 34us/sample - loss: 32811910.9570 - mean_squared_error: 32811912.0000
Epoch 917/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 32821045.1290 - mean_squared_error: 32821046.0000
Epoch 918/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 32818120.2841 - mean_squared_error: 32818116.0000
Epoch 919/1000
1070/1070 [==============================] - 0s 33us/sample - loss: 32807152.8505 - mean_squared_error: 32807146.0000
Epoch 920/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 32809342.9533 - mean_squared_error: 32809342.0000
Epoch 921/1000
1070/1070 [==============================] - 0s 29us/sample - loss: 3

1070/1070 [==============================] - 0s 31us/sample - loss: 32732075.7981 - mean_squared_error: 32732078.0000
Epoch 976/1000
1070/1070 [==============================] - 0s 35us/sample - loss: 32721769.7495 - mean_squared_error: 32721772.0000
Epoch 977/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 32720122.7327 - mean_squared_error: 32720122.0000
Epoch 978/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 32719496.8037 - mean_squared_error: 32719498.0000
Epoch 979/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 32719973.8393 - mean_squared_error: 32719970.0000
Epoch 980/1000
1070/1070 [==============================] - 0s 31us/sample - loss: 32716656.5159 - mean_squared_error: 32716654.0000
Epoch 981/1000
1070/1070 [==============================] - 0s 32us/sample - loss: 32711275.6785 - mean_squared_error: 32711272.0000
Epoch 982/1000
1070/1070 [==============================] - 0s 30us/sample - loss: 3

In [21]:
ypred=reg.predict(x_test)

In [22]:
ypred

array([[ 9127.71   ],
       [ 9647.308  ],
       [44662.023  ],
       [16658.357  ],
       [ 4733.7275 ],
       [ 1979.2539 ],
       [ 3558.9343 ],
       [14868.567  ],
       [ 9077.218  ],
       [ 6959.9473 ],
       [ 4682.355  ],
       [ 9169.889  ],
       [ 9606.525  ],
       [ 4539.697  ],
       [25706.879  ],
       [10736.917  ],
       [ 9274.101  ],
       [ 5209.6353 ],
       [ 6914.353  ],
       [25277.896  ],
       [32779.164  ],
       [14576.438  ],
       [12570.741  ],
       [31065.662  ],
       [ 4561.348  ],
       [ 8680.413  ],
       [ 1678.168  ],
       [10344.567  ],
       [ 4790.507  ],
       [ 8890.797  ],
       [ 8816.466  ],
       [47581.18   ],
       [14622.12   ],
       [12800.113  ],
       [18107.398  ],
       [ 6016.9346 ],
       [11350.194  ],
       [32806.133  ],
       [34781.78   ],
       [ 6656.221  ],
       [ 4252.0327 ],
       [ 2935.4065 ],
       [28827.223  ],
       [45409.     ],
       [27704.98   ],
       [ 6

In [23]:
y_test

array([ 9724.53    ,  8547.6913  , 45702.02235 , 12950.0712  ,
        9644.2525  ,  4500.33925 ,  2198.18985 , 11436.73815 ,
        7537.1639  ,  5425.02335 ,  6753.038   , 10493.9458  ,
        7337.748   ,  4185.0979  , 18310.742   , 10702.6424  ,
       12523.6048  ,  3490.5491  ,  6457.8434  , 33475.81715 ,
       23967.38305 , 12643.3778  , 23045.56616 , 23065.4207  ,
        1674.6323  ,  4667.60765 ,  3732.6251  ,  7682.67    ,
        3756.6216  ,  8413.46305 ,  8059.6791  , 48970.2476  ,
       12979.358   , 20630.28351 , 14571.8908  ,  4137.5227  ,
        8347.1643  , 51194.55914 , 40003.33225 ,  1880.487   ,
        5458.04645 ,  2867.1196  , 20149.3229  , 47496.49445 ,
       36149.4835  , 26018.95052 , 19749.38338 ,  6940.90985 ,
        4718.20355 , 22192.43711 ,  2899.48935 , 18838.70366 ,
       23568.272   , 46255.1125  , 24227.33724 ,  3268.84665 ,
        2322.6218  ,  8827.2099  , 14478.33015 , 13112.6048  ,
        1253.936   , 46718.16325 , 13919.8229  ,  9630.

In [24]:
dataset.head(10)

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [25]:
yp=reg.predict(sc.transform(ct.transform([[19,"female",27.900,0,"yes","southwest"]])))

In [26]:
yp

array([[21664.031]], dtype=float32)

In [29]:
yp=reg.predict(sc.transform(ct.transform([[18,"male",33.770,1,"no","southeast"]])))

In [30]:
yp

array([[4279.571]], dtype=float32)