In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("Bank_Personal_Loan_Modelling.csv")

In [3]:
dataset.head(5)

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [4]:
dataset.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
ID                    5000 non-null int64
Age                   5000 non-null int64
Experience            5000 non-null int64
Income                5000 non-null int64
ZIP Code              5000 non-null int64
Family                5000 non-null int64
CCAvg                 5000 non-null float64
Education             5000 non-null int64
Mortgage              5000 non-null int64
Personal Loan         5000 non-null int64
Securities Account    5000 non-null int64
CD Account            5000 non-null int64
Online                5000 non-null int64
CreditCard            5000 non-null int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [7]:
dataset.drop(columns=["ID","ZIP Code"],inplace=True)

In [9]:
dataset.head()

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1

In [10]:
x=dataset.iloc[:,[0,1,2,3,4,5,6,8,9,10,11]].values
y=dataset.iloc[:,7].values

In [11]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [12]:
x

array([[25.,  1., 49., ...,  0.,  0.,  0.],
       [45., 19., 34., ...,  0.,  0.,  0.],
       [39., 15., 11., ...,  0.,  0.,  0.],
       ...,
       [63., 39., 24., ...,  0.,  0.,  0.],
       [65., 40., 49., ...,  0.,  1.,  0.],
       [28.,  4., 83., ...,  0.,  1.,  1.]])

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) #test_size=0.2 is 20% testing data

In [14]:
x_train.shape

(4000, 11)

In [15]:
x_test.shape

(1000, 11)

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [17]:
from tensorflow.keras.models import Sequential #used to initialize
from tensorflow.keras.layers import Dense #used to add layers

In [18]:
ann=Sequential()

In [20]:
ann.add(Dense(11,kernel_initializer ="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [21]:
ann.add(Dense(22,kernel_initializer ="random_uniform",activation="relu"))

In [23]:
ann.add(Dense(1,kernel_initializer ="random_uniform",activation="sigmoid"))

In [25]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"]) #nick name for batch gradient is adam.

In [27]:
ann.fit(x_train,y_train,batch_size=32,epochs=20)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/20
4000/4000 [==============================] - 0s 119us/sample - loss: 0.5434 - acc: 0.8985
Epoch 2/20
4000/4000 [==============================] - 0s 50us/sample - loss: 0.2116 - acc: 0.9025
Epoch 3/20
4000/4000 [==============================] - 0s 49us/sample - loss: 0.1641 - acc: 0.9025
Epoch 4/20
4000/4000 [==============================] - 0s 48us/sample - loss: 0.1321 - acc: 0.9260
Epoch 5/20
4000/4000 [==============================] - 0s 49us/sample - loss: 0.1051 - acc: 0.9655
Epoch 6/20
4000/4000 [==============================] - 0s 48us/sample - loss: 0.0890 - acc: 0.9710
Epoch 7/20
4000/4000 [==============================] - 0s 49us/sample - loss: 0.0801 - acc: 0.9762
Epoch 8/20
4000/4000 [==============================] - 0s 51us/sample - loss: 0.0741 - acc: 0.9765
Epoch 9/20
4000/4000 [==============================] - 0s 57us/sample - loss: 0.0708 - acc: 0.9765
Epoch

In [28]:
ypred=ann.predict(x_test)

In [29]:
ypred

array([[0.00000000e+00],
       [2.58684158e-05],
       [5.44607639e-04],
       [2.03022361e-03],
       [2.08680928e-02],
       [5.65350056e-05],
       [7.99827814e-01],
       [9.79406714e-01],
       [5.46491742e-02],
       [8.64267349e-07],
       [4.09185886e-05],
       [1.13180578e-02],
       [4.52995300e-06],
       [7.46083260e-03],
       [1.06421918e-01],
       [5.59759140e-03],
       [2.53319740e-06],
       [4.24563885e-04],
       [3.12924385e-06],
       [4.11966443e-03],
       [9.29832458e-06],
       [1.19209290e-07],
       [2.54293084e-02],
       [9.79406714e-01],
       [5.03659248e-06],
       [2.90870667e-05],
       [9.78842258e-01],
       [7.44318545e-01],
       [8.94069672e-08],
       [4.16278839e-04],
       [4.44859266e-04],
       [2.86102295e-06],
       [1.81615353e-03],
       [4.94062901e-04],
       [5.36024570e-04],
       [3.09884548e-04],
       [5.96553087e-04],
       [5.49972057e-04],
       [2.19851732e-03],
       [7.05650449e-03],


In [30]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,

In [35]:
dataset.head(10)

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   
5   37          13      29       4    0.4          2       155              0   
6   53          27      72       2    1.5          2         0              0   
7   50          24      22       1    0.3          3         0              0   
8   35          10      81       3    0.6          2       104              0   
9   34           9     180       1    8.9          3         0              1   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1  
5                   0           0       1           0  
6                   0           0       1           0  
7                   0           0       0           1  
8                   0           0       1           0  
9                   0           0       0           0

In [32]:
ann.predict_classes(sc.transform([[25,1,49,4,1.6,1,0,1,0,0,0]]))

array([[0]])

In [33]:
ann.predict_classes(sc.transform([[45,19,34,3,1.5,1,0,1,0,0,0]]))

array([[0]])

In [36]:
ann.predict_classes(sc.transform([[34,9,180,1,8.9,3,0,0,0,0,0]]))

array([[1]])

In [37]:
ypred>0.5

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [

In [39]:
yp=ann.predict_classes(sc.transform([[34,9,180,1,8.9,3,0,0,0,0,0]]))

In [40]:
yp>0.5

array([[ True]])

In [41]:
dataset.head(5)

Age  Experience  Income  Family  CCAvg  Education  Mortgage  Personal Loan  \
0   25           1      49       4    1.6          1         0              0   
1   45          19      34       3    1.5          1         0              0   
2   39          15      11       1    1.0          1         0              0   
3   35           9     100       1    2.7          2         0              0   
4   35           8      45       4    1.0          2         0              0   

   Securities Account  CD Account  Online  CreditCard  
0                   1           0       0           0  
1                   1           0       0           0  
2                   0           0       0           0  
3                   0           0       0           0  
4                   0           0       0           1