In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("healthcare.csv")

In [3]:
dataset.head(5)

id  gender   age  hypertension  heart_disease ever_married  \
0   9046    Male  67.0             0              1          Yes   
1  51676  Female  61.0             0              0          Yes   
2  31112    Male  80.0             0              1          Yes   
3  60182  Female  49.0             0              0          Yes   
4   1665  Female  79.0             1              0          Yes   

       work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0        Private          Urban             228.69  36.6  formerly smoked   
1  Self-employed          Rural             202.21   NaN     never smoked   
2        Private          Rural             105.92  32.5     never smoked   
3        Private          Urban             171.23  34.4           smokes   
4  Self-employed          Rural             174.12  24.0     never smoked   

   stroke  
0       1  
1       1  
2       1  
3       1  
4       1

In [4]:
dataset.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [5]:
dataset["bmi"].fillna(dataset["bmi"].mean(),inplace=True)

In [6]:
dataset.isnull().any()

id                   False
gender               False
age                  False
hypertension         False
heart_disease        False
ever_married         False
work_type            False
Residence_type       False
avg_glucose_level    False
bmi                  False
smoking_status       False
stroke               False
dtype: bool

In [7]:
x=dataset.iloc[:,1:11].values
y=dataset.iloc[:,11].values

In [8]:
x

array([['Male', 67.0, 0, ..., 228.69, 36.6, 'formerly smoked'],
       ['Female', 61.0, 0, ..., 202.21, 28.893236911794673,
        'never smoked'],
       ['Male', 80.0, 0, ..., 105.92, 32.5, 'never smoked'],
       ...,
       ['Female', 35.0, 0, ..., 82.99, 30.6, 'never smoked'],
       ['Male', 51.0, 0, ..., 166.29, 25.6, 'formerly smoked'],
       ['Female', 44.0, 0, ..., 85.28, 26.2, 'Unknown']], dtype=object)

In [9]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [10]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
id                   5110 non-null int64
gender               5110 non-null object
age                  5110 non-null float64
hypertension         5110 non-null int64
heart_disease        5110 non-null int64
ever_married         5110 non-null object
work_type            5110 non-null object
Residence_type       5110 non-null object
avg_glucose_level    5110 non-null float64
bmi                  5110 non-null float64
smoking_status       5110 non-null object
stroke               5110 non-null int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.1+ KB


In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([("oh",OneHotEncoder(),[0,4,5,6,9])],remainder="passthrough")
#coverts data into binary form
x=ct.fit_transform(x)

In [12]:
x.shape

(5110, 21)

In [13]:
y.shape

(5110,)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0) #test_size=0.2 is 20% testing data

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [16]:
from tensorflow.keras.models import Sequential #used to initialize
from tensorflow.keras.layers import Dense #used to add layers

In [17]:
ann=Sequential()

In [18]:
ann.add(Dense(10,kernel_initializer ="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [19]:
ann.add(Dense(20,kernel_initializer ="random_uniform",activation="relu"))

In [20]:
ann.add(Dense(1,kernel_initializer ="random_uniform",activation="sigmoid"))

In [21]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"]) #nick name for batch gradient is adam.

In [22]:
ann.fit(x_train,y_train,batch_size=32,epochs=50)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/50
4088/4088 [==============================] - 0s 77us/sample - loss: 0.5049 - acc: 0.9477
Epoch 2/50
4088/4088 [==============================] - 0s 35us/sample - loss: 0.1786 - acc: 0.9523
Epoch 3/50
4088/4088 [==============================] - 0s 36us/sample - loss: 0.1637 - acc: 0.9523
Epoch 4/50
4088/4088 [==============================] - 0s 36us/sample - loss: 0.1593 - acc: 0.9523
Epoch 5/50
4088/4088 [==============================] - 0s 37us/sample - loss: 0.1565 - acc: 0.9523
Epoch 6/50
4088/4088 [==============================] - 0s 34us/sample - loss: 0.1547 - acc: 0.9523
Epoch 7/50
4088/4088 [==============================] - 0s 35us/sample - loss: 0.1535 - acc: 0.9523
Epoch 8/50
4088/4088 [==============================] - 0s 42us/sample - loss: 0.1521 - acc: 0.9523
Epoch 9/50
4088/4088 [==============================] - 0s 46us/sample - loss: 0.1510 - acc: 0.9523
Epoch 

In [25]:
ypred=ann.predict(x_test)

In [26]:
ypred

array([[6.1948538e-01],
       [5.9604645e-08],
       [3.2558739e-02],
       ...,
       [6.5353215e-03],
       [1.4494917e-01],
       [3.1713168e-03]], dtype=float32)

In [27]:
y_test

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [38]:
dataset.head(1500)

id  gender    age  hypertension  heart_disease ever_married  \
0      9046    Male  67.00             0              1          Yes   
1     51676  Female  61.00             0              0          Yes   
2     31112    Male  80.00             0              1          Yes   
3     60182  Female  49.00             0              0          Yes   
4      1665  Female  79.00             1              0          Yes   
5     56669    Male  81.00             0              0          Yes   
6     53882    Male  74.00             1              1          Yes   
7     10434  Female  69.00             0              0           No   
8     27419  Female  59.00             0              0          Yes   
9     60491  Female  78.00             0              0          Yes   
10    12109  Female  81.00             1              0          Yes   
11    12095  Female  61.00             0              1          Yes   
12    12175  Female  54.00             0              0          Yes   
13     8213    Male  78.00             0              1          Yes   
14     5317  Female  79.00             0              1          Yes   
15    58202  Female  50.00             1              0          Yes   
16    56112    Male  64.00             0              1          Yes   
17    34120    Male  75.00             1              0          Yes   
18    27458  Female  60.00             0              0           No   
19    25226    Male  57.00             0              1           No   
20    70630  Female  71.00             0              0          Yes   
21    13861  Female  52.00             1              0          Yes   
22    68794  Female  79.00             0              0          Yes   
23    64778    Male  82.00             0              1          Yes   
24     4219    Male  71.00             0              0          Yes   
25    70822    Male  80.00             0              0          Yes   
26    38047  Female  65.00             0              0          Yes   
27    61843    Male  58.00             0              0          Yes   
28    54827    Male  69.00             0              1          Yes   
29    69160    Male  59.00             0              0          Yes   
...     ...     ...    ...           ...            ...          ...   
1470  52559    Male  18.00             0              0           No   
1471    937    Male   7.00             0              0           No   
1472  41271    Male  68.00             1              0          Yes   
1473  66893    Male  49.00             1              0          Yes   
1474  21491  Female  80.00             0              0          Yes   
1475  51806    Male  31.00             0              0          Yes   
1476  59412  Female  25.00             0              0          Yes   
1477    742  Female  39.00             0              0           No   
1478  42902    Male  35.00             0              0          Yes   
1479  43059  Female  71.00             0              0          Yes   
1480  61512  Female  71.00             0              0          Yes   
1481  10943  Female  40.00             0              0          Yes   
1482  11447  Female  41.00             0              0          Yes   
1483  29233    Male   2.00             0              0           No   
1484  17762  Female   3.00             0              0           No   
1485  46284    Male  53.00             1              0          Yes   
1486   1405    Male   1.88             0              0           No   
1487  38493    Male  60.00             1              1          Yes   
1488  57953  Female   5.00             0              0           No   
1489  30746  Female  30.00             0              0          Yes   
1490  16949  Female  49.00             1              0          Yes   
1491  45297    Male  68.00             1              0          Yes   
1492  40251  Female  23.00             0              0           No   
1493  27013    Male   2.00             0         

In [30]:
yp=ann.predict(sc.transform(ct.transform([["Male",67.0,0,1,"Yes","Private","Urban",228.69,36.600000,"formerly smoked"]])))

In [31]:
yp

array([[0.25383225]], dtype=float32)

In [51]:
yp>0.1

array([[False]])

In [39]:
yp=ann.predict(sc.transform(ct.transform([["Male",64.00,0,0,"Yes","Self-employed","Rural",210.00,30.700000,"formerly smoked"]])))

In [40]:
yp

array([[0.03143508]], dtype=float32)

In [47]:
yp>0.001

array([[False]])

In [48]:
yp=ann.predict(sc.transform(ct.transform([["Female",23.00,0,0,"No","Private","Rural",65.90,21.500000,"never smoked"]])))

In [49]:
yp

array([[0.00014944]], dtype=float32)

In [50]:
yp>0.0001

array([[ True]])